

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE DATABASE IF NOT EXISTS newspaper;

ALTER DATABASE newspaper CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci;
